version: '3.7'


# container to run tests and other developer activities
services:
  php:
    container_name: value-object
    image: value-object
    build:
      context: php
    volumes:
      - ./../:/var/app:cached
